# -*- coding: utf-8 -*-
"""Branch_performance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8R43jWVY3lWZDZgDBRb_YWujzFSrGf-
"""

branch_name="Madurai branch" #variable used in the code
revenue=85000
cost=52000

#claculations done in this program
profit_margin=(revenue-cost)/revenue
if profit_margin>0.30:
  rating="Excellent"
elif profit_margin>0.15:
  rating="Good"
else:
  rating="Needs improvement"

print(type(branch_name))
print(type(revenue))
print(type(profit_margin))

#formatting output
print(f'{branch_name}|margin:{profit_margin:.1%}|rating: {rating}')